name: Workflow_Actions

on: [push]

jobs:
  run-github-actions:
    runs-on: windows-lastet
    steps:
      - name: Actions
        id: greet
        uses: https://github.com/actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greething time
        run: echo"${{steps.greet.outputs.time}}"
      
  